language: python
python:
 - 3.7

install:
 - pip install -r requirements.txt

before_script:
 - python manage.py migrate
 - python manage.py collectstatic --noinput

script:
 - back --check .
 - flake 8 . 
 - coverage run --source=swe1,polls manage.py test

after_script:
 - coveralls
